version: '3.5'

services:
  db:
    image: postgres
    container_name: postgres_handbooks
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_USER: dj_admin
      POSTGRES_DB: db01
      PGDATA: /data
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "54321:5432"