# Generated by Django 4.1.2 on 2022-10-20 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('identifier', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='код')),
                ('title', models.CharField(max_length=300, verbose_name='наименование справочника')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='VersionHandbook',
            fields=[
                ('identifier', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50, verbose_name='версия')),
                ('date_start', models.DateField(verbose_name='Дата начала действия версии')),
                ('handbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.handbook')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('identifier', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, verbose_name='код')),
                ('value', models.CharField(max_length=300, verbose_name='значение элемента')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.versionhandbook')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.AddConstraint(
            model_name='versionhandbook',
            constraint=models.UniqueConstraint(fields=('handbook', 'version'), name='unique_version'),
        ),
        migrations.AddConstraint(
            model_name='versionhandbook',
            constraint=models.UniqueConstraint(fields=('handbook', 'date_start'), name='unique_data'),
        ),
        migrations.AddConstraint(
            model_name='element',
            constraint=models.UniqueConstraint(fields=('version', 'code'), name='unique_element'),
        ),
    ]
