# Generated by Django 4.1.2 on 2022-10-20 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='handbook',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='versionhandbook',
            name='identifier',
        ),
        migrations.AddField(
            model_name='element',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa35165b-18ea-4ed4-aa06-7114fcdaf72e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='handbook',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6da856f7-f173-49ac-ba47-0a5a17c80f34'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='versionhandbook',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5554da98-c25a-409c-af00-d5ebd56175b4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
