# Generated by Django 4.1.2 on 2022-10-21 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0002_remove_element_identifier_remove_handbook_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1bd05e3d-fa04-4329-a26d-1efa55b8faf9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='handbook',
            name='id',
            field=models.UUIDField(default=uuid.UUID('51c15843-6040-44f0-b343-5c20ffc5c827'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='versionhandbook',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8d26bc05-ff65-4c07-8405-1e304f294960'), editable=False, primary_key=True, serialize=False),
        ),
    ]
