# Generated by Django 4.1.2 on 2022-10-23 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0004_alter_element_id_alter_handbook_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='handbooks.versionhandbook', verbose_name='Версия справочника'),
        ),
        migrations.AlterField(
            model_name='versionhandbook',
            name='handbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version', to='handbooks.handbook', verbose_name='Справочник'),
        ),
    ]
